#!/bin/bash

echo 'apt::install-recommends "false";' | sudo tee /etc/apt/apt.conf.d/90local

PKGS=(zsh vim tmux lnav curl gnupg fzf)
echo "install some essentials"
# shellcheck disable=SC2068
sudo apt install ${PKGS[@]} --yes

curl -L https://github.com/linuxmaniac.keys >> ~/.ssh/authorized_keys
if which gpg ; then
    gpg --keyserver keyring.debian.org --recv-keys 8F19CADCD42A42D45563730C51A09B18CF5A5068
    gpg --list-keys --fingerprint --with-colons | \
        sed -E -n -e 's/^fpr:::::::::([0-9A-F]+):$/\1:6:/p' | \
        gpg --import-ownertrust
fi

# debian
wget --quiet --ca-directory /dev/null \
  --ca-certificate /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt \
  -O ~/.ssh/debian_known_hosts https://db.debian.org/debian_known_hosts

# oh-my-zsh
(
  cd /tmp/ || exit 1
  mv ~/.oh-my-zsh/custom/ /tmp && rm -rf ~/.oh-my-zsh/
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  mv /tmp/custom/* ~/.oh-my-zsh/custom/
)

if ! apt-cache show zsh-theme-powerlevel9k >/dev/null ; then
  ZSH_VERSION=$(zsh --version|awk '{ print $2 }')
  case $ZSH_VERSION in
    [1-4]\.*|5\.0\.*) branch=v0.6.6;;
    *) branch=master;;
  esac
  git clone https://github.com/bhilburn/powerlevel9k.git \
    ~/.oh-my-zsh/themes/powerlevel9k
  if [ $branch != master ]; then
    (
      echo "zsh version $ZSH_VERSION unsupported for powerlevel9k going to v0.6.6"
      cd ~/.oh-my-zsh/themes/powerlevel9k || exit 1
      git checkout -b v0.6.6 v0.6.6
    )
  fi
  sudo apt install fonts-powerline --yes
else
  sudo apt install zsh-theme-powerlevel9k --yes
  (
    cd ~/.oh-my-zsh/themes/ || exit 1
    ln -s /usr/share/powerlevel9k .
  )
fi

# zsh plugins
sudo apt install zsh-syntax-highlighting zsh-autosuggestions

sudo chsh -s /bin/zsh "$(whoami)"

echo "set yadm repo to SSH"
yadm remote set-url origin git@github.com:linuxmaniac/dotfiles.git
yadm remote update

# tmux packages
sudo apt install tmux-plugin-manager tmux-themepack-jimeh

# vim packages
sudo apt install vim-airline vim-airline-themes vim-gitgutter
